import Head from "next/head";
import About from "../Components/About";
import Contact from "../Components/Contact";
import Header from "../Components/Header";
import Main from "../Components/Main";
import Projects from "../Components/Projects";
import Skills from "../Components/Skills";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dan | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      {/* <Contact /> */}
    </div>
  );
}
